# Generated by Django 5.1.5 on 2025-02-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courtapp', '0004_requesttrial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestTrial',
        ),
    ]
