# Generated by Django 5.1.5 on 2025-02-25 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtapp', '0005_delete_requesttrial'),
        ('userapp', '0036_remove_trial_note_alter_register_is_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='court_schedule', to=settings.AUTH_USER_MODEL)),
                ('jury', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jury_schedule', to='courtapp.jury')),
                ('lawyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_schedule', to=settings.AUTH_USER_MODEL)),
                ('trial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trial_schedule', to='userapp.trial')),
            ],
        ),
    ]
