# Generated by Django 5.1.5 on 2025-02-25 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courtapp', '0006_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='date',
            new_name='scheduled_date',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='time',
            new_name='scheduled_time',
        ),
    ]
