# Generated by Django 5.1.5 on 2025-02-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courtapp', '0007_rename_date_schedule_scheduled_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='court',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='lawyer',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='trial',
        ),
    ]
