# Generated by Django 5.1.5 on 2025-03-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtapp', '0008_remove_schedule_court_remove_schedule_lawyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='reject_reason',
            field=models.TextField(max_length=100000, null=True),
        ),
    ]
