# Generated by Django 5.1.5 on 2025-03-02 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtapp', '0009_schedule_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='trial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trial_schedule', to='courtapp.law'),
        ),
    ]
