# Generated by Django 5.1.5 on 2025-03-03 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtapp', '0010_schedule_trial'),
        ('userapp', '0037_trial_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='trial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trial_schedule', to='userapp.trial'),
        ),
    ]
