# Generated by Django 5.1.5 on 2025-03-10 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtapp', '0011_alter_schedule_trial'),
        ('userapp', '0037_trial_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=100000, null=True)),
                ('file', models.FileField(null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_report', to='courtapp.schedule')),
                ('trial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trial_report', to='userapp.trial')),
            ],
        ),
    ]
