# Generated by Django 5.1.5 on 2025-03-10 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courtapp', '0012_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='trial',
        ),
    ]
