# Generated by Django 5.1.5 on 2025-03-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtapp', '0013_remove_report_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
