# Generated by Django 5.1.5 on 2025-02-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_register_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='barcouncil_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='specialization',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
