# Generated by Django 5.1.5 on 2025-02-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_register_barcouncil_number_register_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='availability',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='bio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='qualification',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
