# Generated by Django 5.1.5 on 2025-02-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_register_availability_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='availability_from',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='availability_to',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
