# Generated by Django 5.1.5 on 2025-02-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_register_availability_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='court_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
