# Generated by Django 5.1.5 on 2025-02-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_alter_register_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='availability_from',
            field=models.TimeField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='bio',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
