# Generated by Django 5.1.5 on 2025-02-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_alter_register_availability_from_alter_register_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='availability_from',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
