# Generated by Django 5.1.5 on 2025-02-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_alter_register_availability_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='availability_from',
        ),
        migrations.RemoveField(
            model_name='register',
            name='availability_to',
        ),
        migrations.AddField(
            model_name='register',
            name='consultation_mode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
