# Generated by Django 5.1.5 on 2025-02-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
