# Generated by Django 5.1.5 on 2025-02-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
