# Generated by Django 5.1.5 on 2025-02-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='content',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='bio',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
