# Generated by Django 5.1.5 on 2025-02-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_bookings_content_alter_register_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
