# Generated by Django 5.1.5 on 2025-02-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_bookings_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='content',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
