# Generated by Django 5.1.5 on 2025-02-19 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0024_alter_law_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Law',
        ),
    ]
