# Generated by Django 5.1.5 on 2025-02-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0026_requesttrial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttrial',
            name='date',
        ),
        migrations.RemoveField(
            model_name='requesttrial',
            name='time',
        ),
        migrations.AddField(
            model_name='requesttrial',
            name='requested_date',
            field=models.DateField(null=True),
        ),
    ]
