# Generated by Django 5.1.5 on 2025-02-23 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0027_remove_requesttrial_date_remove_requesttrial_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestTrial',
        ),
    ]
