# Generated by Django 5.1.5 on 2025-02-23 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0028_delete_requesttrial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField(null=True)),
                ('content', models.FileField(null=True, upload_to='uploads/')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='court_request', to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_request', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
