# Generated by Django 5.1.5 on 2025-02-23 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0029_requesttrial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestTrial',
            new_name='RequestForTrial',
        ),
    ]
