# Generated by Django 5.1.5 on 2025-02-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0030_rename_requesttrial_requestfortrial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfortrial',
            name='note',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
