# Generated by Django 5.1.5 on 2025-02-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0031_requestfortrial_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestForTrial',
            new_name='Trial',
        ),
    ]
