# Generated by Django 5.1.5 on 2025-02-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0032_rename_requestfortrial_trial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trial',
            name='requested_date',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='user',
        ),
    ]
