# Generated by Django 5.1.5 on 2025-02-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0033_remove_trial_requested_date_remove_trial_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='court_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
