# Generated by Django 5.1.5 on 2025-02-24 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0034_trial_court_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.bookings'),
        ),
    ]
