# Generated by Django 5.1.5 on 2025-02-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0035_trial_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trial',
            name='note',
        ),
        migrations.AlterField(
            model_name='register',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
