# Generated by Django 5.1.5 on 2025-02-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0036_remove_trial_note_alter_register_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='response',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
